# Site settings
title: Stephen Smithwick's Slightly Awesome Blog
email: stephen.smithwick@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A place to find out about Stephen Smithwick and to read his sporadic
  musings on Software Development.
baseurl: ""
url: "https://StephenSmithwick.github.io" # the base hostname & protocol for your site
twitter_username: S_Smithwick
github_username:  StephenSmithwick

# Build settings
markdown: kramdown
