# Site settings
title: Stephen Smithwick's Site
email: stephen.smithwick@domain.com
description: >
  Welcome to my humble github Page.  A place to collect information about myself and notes
  for myself in the future
baseurl: ""
url: "https://StephenSmithwick.github.io" # the base hostname & protocol for your site
github_username:  StephenSmithwick
logo: images/logo.jpeg
show_downloads: true
google_analytics: UA-60117878-2

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
